#! /bin/sh

# source ~/scripts/enforce_monitor_position DP-0 '^1' &
sxhkd &

bspc monitor DP-2 -n right -d I II III IV V
bspc monitor DP-4 -n center -d VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^5' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
